# Generated by Django 3.2.6 on 2021-11-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflixuser',
            name='user_token',
            field=models.UUIDField(default='SZUtzqwl', editable=False, primary_key=True, serialize=False),
        ),
    ]
