# Generated by Django 3.2.6 on 2021-11-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_netflixuser_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflixuser',
            name='user_token',
            field=models.CharField(default='de5d2435', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
