# Generated by Django 3.2.6 on 2021-11-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_netflixuser_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='netflixuser',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='netflixuser',
            name='user_token',
            field=models.CharField(default='113e0c2c', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
