# Generated by Django 3.2.6 on 2021-11-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_netflixuser_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflixuser',
            name='user_token',
            field=models.CharField(default='ef4ac308', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
